# this should be used in conjunction with helionotebook-base environment
name: heliocloud-notebook-py
channels:
- conda-forge
- nodefaults
dependencies:
#  - gfortran_linux-64  # - gfortran=11.2  # needed for ffnet dependency of spacepy
#  - gcc_linux-64  # Added to help matplotlib wheel build
#  - gxx_linux-64  # Added to help matplotlib wheel build
#  - jupyter-book  # =0.15.1
#- drms
#- fastparquet
#  - glob2 
#  - html5lib
#  - ipympl
#- plasmapy
#- py-spy
#- pyhdf 
#- sunpy
# - sgp4
# #install this stuff
 - specutils
 - photutils
 - xlrd
 - xlwt
