# Note: this environment will be merged with the panhelio-notebook/environment.yml
# by conda-lock. Only put things here that are not already in the other files
name: helio-ml-trch-notebook
channels:
 - conda-forge
 - nodefaults
dependencies:
 - jupyterlab-nvdashboard
 - gpytorch
 - pytorch>=2.0.0=*cuda118*
   # - torchvision>=0.15.1=*cuda118*
