# Note: this environment will be merged with the panhelio-notebook/environment.yml
# by conda-lock. Only put things here that are not already in the other files
name: helio-daskhub-mltf
channels:
 - conda-forge
 - nodefaults
dependencies:
 - tensorflow>=2.14.0=*cuda118*
 - cuda-version>=11.8
 - cudatoolkit=11.8.0
 - jax
 - jupyterlab-nvdashboard
 - keras-cv
# - opencv
