name: helio-notebook-base
channels:
 - conda-forge
 - nodefaults
 - nvidia
dependencies:
 - python=3.*
# - pangeo-notebook=2022.09.21
 - pip
# - adlfs - azure filesystem support 
# - argopy
 - awscli
 - boto3
# - bottleneck
# - cartopy >= 0.20.0
# - cfgrib -- unidata common format from grib files 
# - ciso
# - dask-gateway
# - dask-labextension
# - dask-ml
# - datashader
# - descartes
# - earthdata
# - eofs
# - erddapy
# - esmpy
# - fastjmd95
# - flox
# - fsspec
# - gcm_filters
# - gcsfs
# - gh
# - geocube
# - geogif
# - geopandas
# - geopy
# - geoviews-core
# - git-lfs
# - gsw
# - h5netcdf
#- h5py
# - holoviews
# - hvplot
# - intake
# - intake-esm
# - intake-geopandas
# - intake-stac
# - intake-xarray
 - ipyleaflet
 - ipytree
 - ipywidgets
 - jupyter-panel-proxy
 - jupyter-resource-usage
 - jupyterlab-git
 - kerchunk
 - lxml
 - lz4
# - matplotlib-base
# - metpy
 - nb_conda_kernels
 - nbstripout
# - nc-time-axis
# - netcdf4
# - numcodecs
# - numpy
# - pandas
# - panel
# - parcels
 - param!=1.11.0
# - pop-tools
# - prefect=0.15.13
# - pyarrow
# - pycamhd
# - pydap
# - pygeos
# - pystac
# - pystac-client
# - python-blosc
# - python-gist
# - python-graphviz
# - rasterio
# - rechunker
# - rio-cogeo
# - rioxarray
# - rise
 - s3fs>0.5
# - satpy
# - scikit-image
# - scikit-learn
# - scipy
# - seaborn
# - sparse
# - stackstac
# - tiledb-py
# - timezonefinder
# - xarray
# - xarrayutils
# - xarray_leaflet
# - xarray-spatial
# - xcape
# - xcube>=0.9.1
# - xesmf
# - xgcm
# - xhistogram
# - xmip
# - xmitgcm
# - xpublish
# - xrft
# - xskillscore
# - zarr
# - gh-scoped-creds
